//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atonom
{
    using System;
    using System.Collections.Generic;
    
    public partial class CosmicBody
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Weigth { get; set; }
        public int radius { get; set; }
        public string location { get; set; }
    }
}
