//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atonom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planets
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public double Weight { get; set; }
        public string Size { get; set; }
        public int DistanceKM { get; set; }
        public int CircleTimeD { get; set; }
        public int Satellites { get; set; }
    }
}
