//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atonom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stars
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string constellation { get; set; }
        public string Type { get; set; }
        public Nullable<int> Diameter { get; set; }
        public Nullable<int> Distance { get; set; }
        public Nullable<int> Light { get; set; }
    }
}
